### ISSUE TITLE
Unable to create scratch org

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/Salesforce-sfdx-cli-orb#1]
**Orb Version**
alpha

**Describe the bug**

As a part fo the integration tests for this orb, there is a test for a job which is meant to automatically create a scratch org. However, currently this job is failing due to the following:

Link: https://circleci.com/gh/CircleCI-Public/Salesforce-sfdx-cli-orb/213
Command: `sfdx force:org:create -f ./sample/config/project-scratch-def.json -a orb-test`
Error: `ERROR running force:org:create:  We encountered a problem while attempting to configure and approve the Connected App for your org. Verify the Connected App configuration with your Salesforce admin.`

**Comment by gmemstr** [comment]
I believe this is due to the Salesforce instance being used, works fine with my own development instance. Will update!
