### ISSUE TITLE
The <<parameters.version>> logic in sfdx/install is wrong

### ISSUE THREAD

**Issue by vazexqi** [CircleCI-Public/Salesforce-sfdx-cli-orb#4]
**Orb Version**
1.0.0

**Describe the bug**

When I pass a version value to sfdx/install command, it actually triggers the wrong path and installs the Salesforce CLI using the installer instead of passing the version to the npm installation.
When I don't pass a version value to the sfdx/install command, it actually triggers the wrong path and tries to do `npm install sfdx-cli@ --global` (nothing after the @).

**To Reproduce**

1. Reference the orb in your config.yml file.
1. Use the sfdx/install command with/without the version parameter.
1. Observe the behavior by inspecting the output in the CircleCI logs.

**Expected behavior**

It should respect the parameters.version.
If there isn't one, use the Salesforce installer.
If there is one, use the `npm install` method but pass the parameter in.

**Additional context**

See https://github.com/CircleCI-Public/Salesforce-sfdx-cli-orb/blob/master/src/commands/install.yml#L11-L29

**Comment by KyleTryon** [comment]
Thank you @vazexqi. I will try to grab this asap.

**Comment by gmemstr** [comment]
Included in #13, thanks for reporting this!
