### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by dogenzenji8** [CircleCI-Public/Salesforce-sfdx-cli-orb#5]
All builds are failing with the error `Cannot read property 'match' of undefined` when executing the "Install SFDX - NPM" step possibly due to deprecated npm packages. Below is the exact output...

```#!/bin/bash -eo pipefail
command -v npm >/dev/null 2>&1 || { echo >&2 "NPM not installed in the current environment.  Aborting."; exit 1; }
npm install sfdx-cli@ --global
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-18T11_57_59_904Z-debug.log

Exited with code exit status 1```

**Comment by dogenzenji8** [comment]
This is related to #4 in that if the `version` parameter is passed, it forces the sfdx/install command to use the sfdx-cli to do the installation (though it's supposed to force it to use npm) therefore bypassing npm install and this error. At least this functions as a workaround for now.

**Comment by vazexqi** [comment]
_I'm from Salesforce_.

@dogenzenji8 - The error is due to https://github.com/forcedotcom/cli/issues/304. The CLI team is investigating it now. That issue is not due to the CircleCI Orb. Although like you mentioned, it helped expose bug #4 .

Admins: I think you can close this due to it being an issue on our side.

**Comment by dogenzenji8** [comment]
Thanks!
